reddit:
  subreddit: "YourSubreddit"

  credentials:
    username: unexBot
    clientID: YOURID
    clientSecret: YOURSECRED
    password: "YOURPASSWORD"
    operatorUsername: Artraxaron
    appID: "de.rtrx.a.unexbot"

  submissions:
    maxTimeDistance: 3600000
    limit: 30
    waitIntervall: 5000

  messages:
    sent:
      maxTimeDistance: 7200000
      maxWaitForCompletion: 20000
      limit: 25
      waitIntervall: 5000
      subject: Please explain what is unexpected in your submission
      body: |
        Hi, I've noticed you submitted [this](%{Submission}) Submission to r/%{subreddit}.

        Please reply to this message with a short explanation of what is unexpected in your submission.
        Your reply will be posted by me in the comments section of your post.
        If you do not reply to this within %{MinutesUntilRemoval} minutes, your post will be deleted.
        You have a total of %{HoursUntilDrop} hours time to reply and get your post approved,
        but please note that your post won't be visible in the meantime if you didn't reply within the %{MinutesUntilRemoval} minutes.

        *****
        [*Look at my source code on GitHub*](https://github.com/Artraxon/unexBot)
    unread:
      waitIntervall: 5000
      limit: 25
      answerMaxCharacters: 500

  scoring:
    timeUntilRemoval: 600000
    commentBody: |
      **OP sent the following text as an explanation on why this is unexpected:**

      >!%{Reason}!<

      *****
      **Is it a good post?**
      **Then upvote this comment, otherwise downvote it.**

      *****
      [*Look at my source code on Github*](https://github.com/Artraxon/unexBot)


  checks:
    db:
      every: 600000
      forTimes: 8
      comments_amount: 20
      depth: 10
      commentWaitIntervall: 10000

DB:
  password: ""
  username: unexbot
  address: localhost
  db: postgres
